#!/bin/bash

case $BLOCK_BUTTON in
    1|3) amixer -q sset Master toggle  ;;  # right click, toggle mute
    4) amixer -q sset Master 5%+  ;;  # scroll up, increase
    5) amixer -q sset Master 5%-  ;;  # scroll down, decrease
esac

statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
    echo "${volume}%"
    echo "${volume}%"
    echo ""
else
    echo "off"
    echo "off"
    echo ""
fi
