#!/bin/bash

if [ -n "$BLOCK_BUTTON" ]; then
  LC_TIME="el_GR.UTF-8" gsimplecal &
fi

FORMAT="${BLOCK_INSTANCE:-%A, %d %B %Y | %H:%M}"
DATETIME=$(LC_TIME="el_GR.UTF-8" date "+${FORMAT}")

echo "${DATETIME}"
