#!/bin/bash
# Based on https://aur.archlinux.org/packages/playerctl/

INSTANCE="${BLOCK_INSTANCE}"

if [[ "${INSTANCE}" != "" ]]; then
  ARGUMENTS="--player=${INSTANCE}"
fi

ICON_PLAY="➤"
ICON_PAUSE="Ⅱ"
CUR_ICON=""

if [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    $(playerctl ${ARGUMENTS} previous)
    exit
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
    $(playerctl ${ARGUMENTS} play-pause)
    exit
elif [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    $(playerctl ${ARGUMENTS} next)
    exit
fi

# Wait for change.
~/bin/i3blocks/blocks/playerctl-change.py

PLAYER_STATUS=$(playerctl ${ARGUMENTS} status)
if [[ "${PLAYER_STATUS}" = "Not available" ]]; then
    exit
fi

# http://stackoverflow.com/questions/1527049/bash-join-elements-of-an-array#comment37571340_17841619
function join_by { perl -e '$s = shift @ARGV; print join($s, @ARGV);' "$@"; }

INFO_TITLE=$(playerctl ${ARGUMENTS} metadata title)
#INFO_ALBUM=$(playerctl ${ARGUMENTS} metadata album)
INFO_ARTIST=$(playerctl ${ARGUMENTS} metadata artist)

if [[ "${PLAYER_STATUS}" = "Paused" ]]; then
  CUR_ICON="${ICON_PAUSE}"
elif [[ "${PLAYER_STATUS}" = "Playing" ]]; then
  CUR_ICON="${ICON_PLAY}"
fi

INFO=$(join_by ' - ' "${INFO_ARTIST}" "${INFO_TITLE}")
echo "${INFO} ${CUR_ICON}"
echo "${INFO} ${CUR_ICON}"
